[package]
name = "gaman"
version = "0.1.2"
edition = "2024"
description = "PostgreSQL-first, offline schema migration tool with Django-like ergonomics"
license = "MIT"
repository = "https://github.com/vivsh/gaman"
homepage = "https://github.com/vivsh/gaman"
readme = "README.md"
keywords = ["migrations", "postgresql", "database", "schema", "cli"]
categories = ["database", "command-line-utilities"]
exclude = [".env", "output.txt", "tests/", ".github/"]

[dependencies]
argh = "0.1.19"
dotenvy = "0.15.7"
postgres = "0.19"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_yaml = "0.9.34"
thiserror = "2.0.18"
